[versions]
kotlin-core = "2.2.21"
ktlint = "1.2.1"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version = "0.28.1" }
junit-bom = { module = "org.junit:junit-bom", version = "5.14.1" }
mockk-core = { module = "io.mockk:mockk", version = "1.14.6" }

# gradle plugins for build-logic
gradle-plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.23.8" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradle-plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "13.1.0" }

[plugins]
plugin-publish = {id="com.gradle.plugin-publish", version="2.0.0"}
